parameters:
    hub.clock.class: Dothiv\ValueObject\ClockValue
    hub.user.class: Retext\Hub\BackendBundle\Service\UserService
    hub.usertokenfactory.class: Retext\Hub\BackendBundle\Service\UserTokenFactory
    hub.value_validator.class: Retext\Hub\BackendBundle\Service\EntryValueValidator

services:

    hub.clock:
        class: %hub.clock.class%
        arguments:
        - %hub_backend.clock_expr%

    clock: "@hub.clock"

    hub.user:
        class: %hub.user.class%
        arguments:
        - @hub.repo.user
        - @hub.repo.user_token
        - @hub.repo.user_login_link_request
        - @clock

    hub.usertokenfactory:
        class: %hub.usertokenfactory.class%
        arguments:
        - @clock
        - %hub_backend.tokens%

    hub.value_validator:
        class: %hub.value_validator.class%
        arguments:
        - @validator
