language: php

php:
  - 5.6
  - 5.5
  - 5.4

before_script:
  - cp app/config/parameters.yml.travis app/config/parameters.yml  
  - cp app/config/parameters.yml.travis app/config/parameters_test.yml
  - composer install
  - psql -c 'create database travis_ci_test;' -U postgres
  - php app/console doctrine:schema:create

script:
  - phpunit -c app/

after_failure:
  - cd /home/travis/build/retext/hub/
  - sudo cat app/logs/test.log | grep CRITICAL
