imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    # Do not convert variables in camel case (myVar) to snake case "my_var"
    jms_serializer.camel_case_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy

framework:
    #esi:             ~
    translator:      { enabled: true, fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: %assets_version%
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
      ~

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:
      ~
    #java: /usr/bin/java
    filters:
        less:
            node: %node_bin%
            node_paths: [%node_modules%]
            apply_to: "\.less$"
        cssrewrite: ~
    assets:
        angular_js:
            inputs:
            - %kernel.root_dir%/../vendor/components/angularjs/angular.js
        angular_js_resource:
            inputs:
            - %kernel.root_dir%/../vendor/components/angularjs/angular-resource.js
        angular_js_route:
            inputs:
            - %kernel.root_dir%/../vendor/components/angularjs/angular-route.js
        angular_js_cookies:
            inputs:
            - %kernel.root_dir%/../vendor/components/angularjs/angular-cookies.js
        angular_ui_router:
            inputs:
            - %kernel.root_dir%/../vendor/components/angular-ui-router/release/angular-ui-router.js
        angular_ui_bootstrap:
            inputs:
            - %kernel.root_dir%/../vendor/components/jquery/jquery.js
            - %kernel.root_dir%/../vendor/components/bootstrap/ui-bootstrap.js
        angular_ui_bootstrap_tpls:
            inputs:
            - %kernel.root_dir%/../vendor/components/jquery/jquery.js
            - %kernel.root_dir%/../vendor/components/bootstrap/ui-bootstrap-tpls.js

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        path:     %database_path%
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

stof_doctrine_extensions:
    orm:
        default:
            timestampable: true

# Swiftmailer Configuration
swiftmailer:
    transport:  %mailer_transport%
    host:       %mailer_host%
    username:   %mailer_user%
    password:   %mailer_password%
    port:       %mailer_port%
    encryption: %mailer_encryption%
    auth_mode:  %mailer_auth_mode%
    spool:     { type: memory }

nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']
        allow_headers: ['origin', 'accept', 'authorization', 'content-type']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
        expose_headers: []
        max_age: 0
        hosts: []
    paths:
        '^/': ~

jms_serializer:
    visitors:
        json:
            # $ php -r 'echo JSON_UNESCAPED_SLASHES'
            options: 64
